### ISSUE TITLE
Add tests to check that permissions were properly revoked

### ISSUE THREAD

**Issue by bingen** [aragon/dao-templates#34]
[Here](https://github.com/aragon/dao-kits/blob/master/kits/multisig/test/multisig.js#L98) and [here](https://github.com/aragon/dao-kits/blob/master/kits/democracy/test/democracy.js#L109).
Check that all of these worked:
https://github.com/aragon/dao-kits/blob/master/kits/multisig/contracts/MultisigKit.sol#L72
https://github.com/aragon/dao-kits/blob/master/kits/democracy/contracts/DemocracyKit.sol#L65
https://github.com/aragon/dao-kits/blob/master/kits/beta-base/contracts/BetaKitBase.sol#L140
https://github.com/aragon/dao-kits/blob/master/kits/beta-base/contracts/BetaKitBase.sol#L141

**Comment by sohkai** [comment]
@bingen I believe this was done as part of the permissions tests for the democracy and multisig tests?

**Comment by facuspagnuolo** [comment]
Considering this issue as fixed after both democracy and multisig test improvements
