### ISSUE TITLE
KitBase: fetch DAOFactory from aragonPM

### ISSUE THREAD

**Issue by sohkai** [aragon/dao-templates#64]
Seems like it could be a good way to avoid having to recreate kits if the DAOFactory changes over time.

Could be done in a similar manner to how the apps in the beta kits are fetched through aragonPM.

**Comment by facuspagnuolo** [comment]
@sohkai are we registering the `DAOFactory` in aragonPM?

**Comment by sohkai** [comment]
@facuspagnuolo No, not yet. I still think this could be useful, but it adds gas overhead and we generally don't publish new Kernels or ACLs without it being a Big Deal so I wouldn't add this to widely used production kits.
