### ISSUE TITLE
Startup template

### ISSUE THREAD

**Issue by luisivan** [aragon/dao-templates#83]
- Tokens
    - Non-changeable defaults: Transferable, uncapped, 18 decimals
- Voting
    - Changeable defaults: 50% relative support, 0% absolute support, 7 day duration
- Finance
    - Non-changeable defaults: 30 day budget duration
- Payroll: Enable opting out of its installation
    - Changeable defaults: Dai as denomination token (not changeable after initialization)

**Comment by luisivan** [comment]
Should we disallow burning tokens @lkngtn? I don't think you can do that in traditional startups

**Comment by lkngtn** [comment]
I would leave the burn permission un-initialized but not discarded.

**Comment by luisivan** [comment]
Makes sense

**Comment by sohkai** [comment]
Closed by #97
