### ISSUE TITLE
Membership template

### ISSUE THREAD

**Issue by luisivan** [aragon/dao-templates#85]
- Tokens
    - Non-changeable defaults: Non-transferable, capped to 1 per address, 18 decimals
- Voting
    - Non-changeable default: Controls minting and burning tokens
    - Changeable defaults: 50% relative support, 0% absolute support, 7 day duration
- Finance
    - Non-changeable defaults: 30 day budget duration
- Payroll: Enable opting out of its installation
    - Changeable defaults: Dai as denomination token (not changeable after initialization)

**Comment by sohkai** [comment]
Closed by #99
