### ISSUE TITLE
Improve democracy template tests

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/dao-templates#91]
Current democracy template tests can only be run with geth. We should provide support for ganache as well. Additionally, there are multiple steps along the suite that can be simplified using some of the helpers provided in `test-helpers` and `templates-shared`.

**Comment by sohkai** [comment]
In some way, they were designed to be used specifically on geth so we could run these E2E smoke tests against a real node, but I agree running them on ganache would be useful for development and then we can run longer, nightly checks on CI with a real node.
